spring:
  application:
    name: SIG UPA

  # Database settings
  datasource:
    url: jdbc:mysql://localhost:3306/db_sigupa?createDatabaseIfNotExist=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect